spring.application.name=postgresdb
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#port 5432 was in use, so we mapped it to 5433 here and in docker-compose.yml
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
